---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
          - containerPort: 3306
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: maria-root-password
                name: mariadb-secret      
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-internal-service
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb